apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: clear-route-demo
  description: Faster Payment service
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: Tony Stark
