apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hi-james
  description: Faster Payments service
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: Tony Stark
